// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaxGuUhGcSIP47iui4HhJbns1RnB7HI1w',
    appId: '1:808896869581:web:bf34d54c72be92908a2584',
    messagingSenderId: '808896869581',
    projectId: 'flutter-d5813',
    authDomain: 'flutter-d5813.firebaseapp.com',
    storageBucket: 'flutter-d5813.appspot.com',
    measurementId: 'G-WHBCJT70EJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJFm-_UP-zkrVugQAmLpUV1mJKd1B0I9U',
    appId: '1:808896869581:android:de9898a7ac3925a98a2584',
    messagingSenderId: '808896869581',
    projectId: 'flutter-d5813',
    storageBucket: 'flutter-d5813.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4TamU1ibTLINmOsUU7RBF0cROrmzmG-Q',
    appId: '1:808896869581:ios:6941801ef7172e0b8a2584',
    messagingSenderId: '808896869581',
    projectId: 'flutter-d5813',
    storageBucket: 'flutter-d5813.appspot.com',
    iosBundleId: 'com.example.appFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4TamU1ibTLINmOsUU7RBF0cROrmzmG-Q',
    appId: '1:808896869581:ios:6941801ef7172e0b8a2584',
    messagingSenderId: '808896869581',
    projectId: 'flutter-d5813',
    storageBucket: 'flutter-d5813.appspot.com',
    iosBundleId: 'com.example.appFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaxGuUhGcSIP47iui4HhJbns1RnB7HI1w',
    appId: '1:808896869581:web:d49c8a8e70e7bb728a2584',
    messagingSenderId: '808896869581',
    projectId: 'flutter-d5813',
    authDomain: 'flutter-d5813.firebaseapp.com',
    storageBucket: 'flutter-d5813.appspot.com',
    measurementId: 'G-6E9ZEKMJEJ',
  );
}
